version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - broker-kafka
    ports:
      - "12181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    networks:
      - broker-kafka
    ports:
      - "9092:9092"
      - "29094:29094"
    environment:
      KAFKA_LISTENERS: INSIDE://kafka:29094,OUTSIDE://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29094,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "events.all"
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29094
networks:
  broker-kafka:
    driver: bridge